[package]
name = "neondb"
version = "0.1.0"
authors = ["snaztoz <hafidhmn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
